In [3]:
import numpy as np
 
 
arr = np.arange(30).reshape(5, 6)
print(arr)
print()
tran_arr = np.transpose(arr)
print(tran_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [21]:
a = np.linspace(1,5,5)

In [22]:
a

array([ 1.,  2.,  3.,  4.,  5.])

In [23]:
offset = [0,1,2,3]

In [24]:
c = (a*b for b in offset)

In [25]:
c

<generator object <genexpr> at 0x0000000007B06678>

In [26]:
list(c)

[array([ 0.,  0.,  0.,  0.,  0.]),
 array([ 1.,  2.,  3.,  4.,  5.]),
 array([  2.,   4.,   6.,   8.,  10.]),
 array([  3.,   6.,   9.,  12.,  15.])]

In [11]:
c

<generator object <genexpr> at 0x0000000007A63CA8>